### ISSUE TITLE
Force drop-down menu to open

### ISSUE THREAD

**Issue by Lefteris008** [HubSpot/react-select-plus#110]
Hello,

What's the procedure of calling focus() function? I have tried referencing the component via ref attribute but I had no luck in succeeding.

**Comment by TrevorBurnham** [comment]
That should work:

```jsx
<Select ref={(ref) => { if (ref) { ref.focus(); } } } />
```

Are you sure some other component isn't grabbing the focus?

**Comment by TrevorBurnham** [comment]
I see. And does this happen even if your `valueClick` method is empty, or is something in that method responsible?

**Comment by Lefteris008** [comment]
Yes, it happens with whichever body the method has. I suppose, the `onValueClick` property was built to route users who click a selection to another page; its tag, besides, whenever populated, is displayed as a `<a>` -the equivalent of a link. I, however, use it as an alternative way of creating an event listener.

Specifically, I need to capture the entire value of the selected bubble (which, in my case contains other options such as label etc) and update the result list of the select accordingly. I am afraid that building a common event listener on this item's clicks, would not pass the complete `value` object but rather the displayed value.

**Comment by TrevorBurnham** [comment]
Ah, yes, setting that prop (passed through to the `Value` component as `onClick`) prevents the [`mousedown` event from propagating](https://github.com/JedWatson/react-select/blob/c9d027387a77b3695fdfbb3d4de25ffcea9505ee/src/Value.js#L21-L25), so the surrounding component never receives it. Storing a ref to the `Select` and calling `ref.focus()` in the `valueOnClick` should work in principle. But you say you've tried that without success? Have you tried calling it after a timeout (`setTimeout(() => { ref.focus(); }, 0)`)?

Since this behavior is consistent with the upstream react-select project, it's a #wontfix on our end.

**Comment by Lefteris008** [comment]
Yes, I have tried manually calling `focus()` method but with no luck. I feel though that I am using it wrong:

    valueClick(value) {
        this.selection.focus();
    },
    render () {
        return (
	    <div className="section">
                <Select
			multi={this.state.multi}
			ref={(input) => { this.selection = input; }}
			options={options}
                        value={value}
			onValueClick={this.valueClick}				
                />
	    </div>		
	);
    }

**Comment by TrevorBurnham** [comment]
Looks like it's a timing issue, which you can see simply replicated here: https://codepen.io/TrevorBurnham/pen/LQjjrb Focusing an element during a `mousedown` event (as when your `valueClick()` is invoked) doesn't do anything. You can see that wrapping the `focus()` call in even a 0ms timeout fixes the problem: https://codepen.io/TrevorBurnham/pen/oEeeMB

**Comment by Lefteris008** [comment]
Yes, that was it. Thank you so much for your time!
