### ISSUE TITLE
Callback for onSelect?

### ISSUE THREAD

**Issue by nickstanish** [HubSpot/react-select-plus#26]
Would you be open to a PR exposing an onSelect(option) callback for Option? I would like to be able to access the option data immediately when the user select it from the dropdown.

**Comment by nickstanish** [comment]
Closing this because I realized that this can be accomplished with the `onChange` property - by setting the value as an object and having a `labelKey`

**Comment by TrevorBurnham** [comment]
I would recommend against setting `value` to be an object rather than a primitive. As [the docs say](https://github.com/JedWatson/react-select#usage):

> The `value` property of each option should be set to either a string or a number.

Using non-primitive values might work, but there are no guarantees that they'll work with every feature, or that they'll continue to work with future updates.

So I think your best bet is to create a value-option map on your end and perform a lookup from `onChange`. I know that can be a bit inconvenient, but I'm not keen on making additions to the react-select API without a stronger reason than convenience.

**Comment by nickstanish** [comment]
I should have specified that I am referring to the value of the Select (which is an Option and should be an object). I followed the example found [here](https://github.com/JedWatson/react-select/blob/master/examples/src/components/GithubUsers.js)

> Options should be provided as an Array of Objects, each with a value and label property for rendering and searching. You can use a disabled property to indicate whether the option is disabled or not.

**Comment by TrevorBurnham** [comment]
> I should have specified that I am referring to the value of the Select (which is an Option and should be an object)

You've lost me… what do you mean by "the value of the Select" if you're not talking about the `value` in the context of `<Select options={options} value={value} />`, which corresponds to `option.value` for some `option` object in `options` and should be a primitive?
